version: '3.8'

services:
  # 1. Baza Danych (Postgres)
  db:
    image: postgres:13-alpine
    container_name: eso_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eso-network

  # 2. Backend (NestJS)
  backend:
    build: ./backend
    container_name: eso_backend
    ports:
      - "3000:3000"
    environment:
      # DATABASE_URL musi wskazywać na nazwę serwisu 'db', nie localhost!
      DATABASE_URL: "postgresql://user:password@db:5432/esodb?schema=public"
    depends_on:
      - db
    networks:
      - eso-network

  # 3. Frontend (React + Nginx)
  frontend:
    build: ./frontend
    container_name: eso_frontend
    ports:
      - "5173:80" # Mapujemy port 80 kontenera na 5173 twojego komputera
    depends_on:
      - backend
    networks:
      - eso-network

volumes:
  postgres_data:

networks:
  eso-network: